# Generated by Django 6.1.1 on 2026-09-12 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amout', models.IntegerField()),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_status', models.CharField(choices=[('failed', 'Failed'), ('success', 'Success'), ('pending', 'Pending')], default='success')),
                ('transaction_method', models.CharField(choices=[('upi', 'Upi'), ('card', 'Card'), ('netbanking', 'Net Banking')], default='upi')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
    ]
